# NOTICE: Generated By HttpRunner. DO NOT EDIT!
# FROM: demo.yml

from httprunner import HttpRunner, TConfig, TStep


class TestCaseDemo(HttpRunner):
    config = TConfig(
        **{"name": "testcase description", "variables": {}, "path": "demo_test.py"}
    )

    teststeps = [
        TStep(
            **{
                "name": "/graphql/f/p5N7Yr",
                "request": {
                    "headers": {
                        "content-type": "application/json;charset=UTF-8",
                        "sec-fetch-dest": "empty",
                        "sec-fetch-mode": "cors",
                        "sec-fetch-site": "same-origin",
                        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36",
                        "x-csrf-token": "fe6FyqMM2XPa+WcN/1U9RseObm3RzBKWVxFK+0jhWycQI7AmY5kVPyWomjZYbLVTQOZEyfUJ6q1udl4lqwGZlQ==",
                        "x-entry-token": "n5XwdfkJ",
                        "x-gd-ssf": "MTU5MTA2Nzg5Mw==--964a6ec9a93b4be282953f262ed3168b41eaacff",
                    },
                    "json": {
                        "extensions": {
                            "persistedQuery": {
                                "sha256Hash": "4cd6a9aef2820b2c3215f6ddfa87093869461f76f3f2016738f4307268a7df98",
                                "version": 1,
                            }
                        },
                        "operationName": "CreatePublishedFormEntry",
                        "variables": {
                            "input": {
                                "backgroundImage": False,
                                "captchaData": None,
                                "embedded": False,
                                "entryAttributes": {
                                    "field_1": "王五",
                                    "field_2": "13500000000",
                                },
                                "formId": "p5N7Yr",
                                "formMargin": False,
                                "weixinAccessToken": None,
                                "weixinInfo": None,
                                "xFieldWeixinOpenid": None,
                            }
                        },
                    },
                    "method": "POST",
                    "url": "https://staging.jinshuju.net/graphql/f/p5N7Yr",
                },
                "validate": [{"eq": ["status_code", 200]}],
            }
        ),
    ]


if __name__ == "__main__":
    TestCaseDemo().test_start()
