# NOTICE: Generated By HttpRunner. DO NOT EDIT!
# FROM: get_wf.yml

from httprunner import HttpRunner, TConfig, TStep


class TestCaseGetWf(HttpRunner):
    config = TConfig(
        **{
            "name": "testcase description",
            "variables": {},
            "verify": False,
            "path": "get_wf_test.py",
        }
    )

    teststeps = [
        TStep(
            **{
                "name": "/lottery/255/result",
                "request": {
                    "cookies": {
                        "_gd-wheel-fortune_session": "dTdwSkoxWmNOY0Q3bjJ3NUo1WjRiblByM0VBcGFyWXpiK3JKdGkvWlBnVHJjT2h4cFpYTlY5bXJKcE0vZFl5b0ZUWVFkTmQ3Vi9td285UnUrd3lFNVpLQ0ZmRlAwWHpFcm45MkJJQmdGcXFtWUN2QVhQTDFtSjJiY05VWmtZeDlCUW5oVWRkZFQ5VDY1MWY4NzRGeG5PRzJUdGdpY3Q1cFBVYnd6dDZVRklJbWxRZlo3bzNLYlo0Q0xkaEJ6Z3JmLS1iUkcrNERiUEFMMXFla2M4ZmpFb293PT0%3D--231bbb2c7a2b1f87b3b8813a21b78a622a08ffb8"
                    },
                    "headers": {
                        "accept": "application/json, text/javascript, */*; q=0.01",
                        "accept-encoding": "gzip, deflate, br",
                        "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                        "cache-control": "no-cache",
                        "pragma": "no-cache",
                        "referer": "https://wf.staging.jinshujuapp.com/lottery/5/DIoQKq?field_2=&jamr_h=LS0tCi0gRElvUUtxCi0gbk5DNFFPNEwKLSAhcnVieS9vYmplY3Q6QWN0aXZlU3VwcG9ydDo6VGltZVdpdGhab25lCiAgdXRjOiAyMDIwLTA2LTE1IDA2OjUzOjAzLjY2MjE5NDIxMSBaCiAgem9uZTogIXJ1Ynkvb2JqZWN0OkFjdGl2ZVN1cHBvcnQ6OlRpbWVab25lCiAgICBuYW1lOiBBc2lhL1NoYW5naGFpCiAgdGltZTogMjAyMC0wNi0xNSAxNDo1MzowMy42NjIxOTQyMTEgWgo%3D--6b9895c831ab82ed412833003a8d931d&serial_number=12",
                        "sec-fetch-dest": "empty",
                        "sec-fetch-mode": "cors",
                        "sec-fetch-site": "same-origin",
                        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36",
                        "x-csrf-token": "Q6hdZOvdlimnCRulHMlmfIB+gAylWEf9doO5oSXMNApk5WF1q3i3Xz/7x/otSgR5NSZ9m3WWZOCfR6Q0n5dzQA==",
                        "x-requested-with": "XMLHttpRequest",
                    },
                    "method": "GET",
                    "params": {
                        "jamr_h": "LS0tCi0gRElvUUtxCi0gbk5DNFFPNEwKLSAhcnVieS9vYmplY3Q6QWN0aXZlU3VwcG9ydDo6VGltZVdpdGhab25lCiAgdXRjOiAyMDIwLTA2LTE1IDA2OjUzOjAzLjY2MjE5NDIxMSBaCiAgem9uZTogIXJ1Ynkvb2JqZWN0OkFjdGl2ZVN1cHBvcnQ6OlRpbWVab25lCiAgICBuYW1lOiBBc2lhL1NoYW5naGFpCiAgdGltZTogMjAyMC0wNi0xNSAxNDo1MzowMy42NjIxOTQyMTEgWgo=--6b9895c831ab82ed412833003a8d931d",
                        "participant": "",
                    },
                    "url": "https://wf.staging.jinshujuapp.com/lottery/255/result",
                },
                "validate": [
                    {"eq": ["status_code", 200]},
                    {"eq": ["body.success", True]},
                    {"eq": ["body.status", "win"]},
                    {"eq": ["body.code", ""]},
                    {"eq": ["body.prize_id", 256]},
                    {"eq": ["body.title_name", "三等奖"]},
                    {"eq": ["body.prize_name", "三等奖"]},
                    {"eq": ["body.cash_token", "456c93cd"]},
                    {"eq": ["body.winner_id", 4]},
                ],
            }
        ),
    ]


if __name__ == "__main__":
    TestCaseGetWf().test_start()
